### ISSUE TITLE
pkl_to_json.py中list元素越界

### ISSUE THREAD

**Issue by ltcRandomwalk** [HYLZ-2019/FriendsOfFriends#1]
`print("link_cnt top 30: ")
tups = list(link_cnt.items())
tups.sort(key=lambda x: -x[1])
for i in range(30):
    print(tups[i][0]+": "+str(tups[i][1]))
`
如果列表的元素小于30，这个访问将造成越界

**Comment by HYLZ-2019** [comment]
确实，如果你数据中的总节点数小于30，可以修改一下这个数字。
