### ISSUE TITLE
可能需要把微信朋友圈置顶才能正常scroll

### ISSUE THREAD

**Issue by zfthys** [HYLZ-2019/FriendsOfFriends#2]
我的电脑微信版本是3.7.0.29，如果不使用朋友圈的置顶功能，pywinauto.mouse.scroll无法正常滑动朋友圈页面，会使程序反复读取同一个页面的内容

**Comment by HYLZ-2019** [comment]
确实，scroll的行为是“把鼠标移动那个位置，然后滚动滚轮”。如果朋友圈不是鼠标位置处的最上层，滚动就不能正确地使朋友圈往下刷。使用置顶功能、单纯不用其他窗口覆盖它，都能让朋友圈页面处于最上层。
